export const ishiharaPlates = {
  protanopia: {
    plate_2: require('../../assets/images/ishihara/Prot_RG/2.png'),
    plate_3: require('../../assets/images/ishihara/Prot_RG/3.png'),
    plate_5: require('../../assets/images/ishihara/Prot_RG/5.png'),
    plate_5_2: require('../../assets/images/ishihara/Prot_RG/5(2).png'),
    plate_6: require('../../assets/images/ishihara/Prot_RG/6.png'),
    plate_6_2: require('../../assets/images/ishihara/Prot_RG/6(2).png'),
    plate_7: require('../../assets/images/ishihara/Prot_RG/7.png'),
    plate_8: require('../../assets/images/ishihara/Prot_RG/8.png'),
    plate_15: require('../../assets/images/ishihara/Prot_RG/15.png'),
    plate_16: require('../../assets/images/ishihara/Prot_RG/16.png'),
    plate_26: require('../../assets/images/ishihara/Prot_RG/26.png'),
    plate_29: require('../../assets/images/ishihara/Prot_RG/29.png'),
    plate_35: require('../../assets/images/ishihara/Prot_RG/35.png'),
    plate_42: require('../../assets/images/ishihara/Prot_RG/42.png'),
    plate_45: require('../../assets/images/ishihara/Prot_RG/45.png'),
    plate_57: require('../../assets/images/ishihara/Prot_RG/57.png'),
    plate_73: require('../../assets/images/ishihara/Prot_RG/73.png'),
    plate_74: require('../../assets/images/ishihara/Prot_RG/74.png'),
    plate_96: require('../../assets/images/ishihara/Prot_RG/96.png'),
    plate_97: require('../../assets/images/ishihara/Prot_RG/97.png'),
    plate_nada: require('../../assets/images/ishihara/Prot_RG/nada.png'),
    plate_nada_2: require('../../assets/images/ishihara/Prot_RG/nada(2).png'),
    plate_nada_3: require('../../assets/images/ishihara/Prot_RG/nada(3).png'),
    plate_nada_4: require('../../assets/images/ishihara/Prot_RG/nada(4).png'),
  },

  deuteranopia: {
    plate_3: require('../../assets/images/ishihara/Deut_GR/3.png'),
    plate_6: require('../../assets/images/ishihara/Deut_GR/6.png'),
    plate_5: require('../../assets/images/ishihara/Deut_GR/5.png'),
    plate_5_2: require('../../assets/images/ishihara/Deut_GR/5(2).png'),
    plate_7: require('../../assets/images/ishihara/Deut_GR/7.png'),
    plate_7_2: require('../../assets/images/ishihara/Deut_GR/7(2).png'),
    plate_12: require('../../assets/images/ishihara/Deut_GR/12.png'),
    plate_15: require('../../assets/images/ishihara/Deut_GR/15.png'),
    plate_15_2: require('../../assets/images/ishihara/Deut_GR/15(2).png'),
    plate_16: require('../../assets/images/ishihara/Deut_GR/16.png'),
    plate_16_2: require('../../assets/images/ishihara/Deut_GR/16(2).png'),
    plate_16_3: require('../../assets/images/ishihara/Deut_GR/16(3).png'),
    plate_27: require('../../assets/images/ishihara/Deut_GR/27.png'),
    plate_29: require('../../assets/images/ishihara/Deut_GR/29.png'),
    plate_29_2: require('../../assets/images/ishihara/Deut_GR/29(2).png'),
    plate_45: require('../../assets/images/ishihara/Deut_GR/45.png'),
    plate_56: require('../../assets/images/ishihara/Deut_GR/56.png'),
    plate_57: require('../../assets/images/ishihara/Deut_GR/57.png'),
    plate_73: require('../../assets/images/ishihara/Deut_GR/73.png'),
    plate_74: require('../../assets/images/ishihara/Deut_GR/74.png'),
  },

  tritanopia: {
    plate_3: require('../../assets/images/ishihara/Trit_GB/3.png'),
    plate_7: require('../../assets/images/ishihara/Trit_GB/7.png'),
    plate_8: require('../../assets/images/ishihara/Trit_GB/8.png'),
    plate_8_2: require('../../assets/images/ishihara/Trit_GB/8(2).png'),
    plate_9: require('../../assets/images/ishihara/Trit_GB/9.png'),
    plate_19: require('../../assets/images/ishihara/Trit_GB/19.png'),
    plate_25: require('../../assets/images/ishihara/Trit_GB/25.png'),
    plate_36: require('../../assets/images/ishihara/Trit_GB/36.png'),
    plate_36_2: require('../../assets/images/ishihara/Trit_GB/36(2).png'),
    plate_42: require('../../assets/images/ishihara/Trit_GB/42.png'),
    plate_44: require('../../assets/images/ishihara/Trit_GB/44.png'),
    plate_53: require('../../assets/images/ishihara/Trit_GB/53.png'),
    plate_56: require('../../assets/images/ishihara/Trit_GB/56.png'),
    plate_57: require('../../assets/images/ishihara/Trit_GB/57.png'),
    plate_68: require('../../assets/images/ishihara/Trit_GB/68.png'),
    plate_69: require('../../assets/images/ishihara/Trit_GB/69.png'),
    plate_89: require('../../assets/images/ishihara/Trit_GB/89.png'),
    plate_90: require('../../assets/images/ishihara/Trit_GB/90.png'),
    plate_93: require('../../assets/images/ishihara/Trit_GB/93.png'),
    plate_98: require('../../assets/images/ishihara/Trit_GB/98.png'),
  }
};